export const textsFr = [

  // ---------------------------------------- Nourriture ---------------------------------------- //
  "La baguette de pain maison, emblème de la boulangerie française, incarne à la fois la simplicité et l'excellence artisanale. Cette recette iconique, réalisée avec quelques ingrédients de base, offre une expérience culinaire authentique et gratifiante. Pétrir la pâte à la main, sentir les arômes du pain frais emplir la cuisine, puis déguster une baguette croustillante à la sortie du four sont des moments de pure satisfaction.",

  "Le boeuf bourguignon est un plat de viande de boeuf braisée au vin rouge, et servi avec une garniture composée d'oignons grelots, de champignons et de lardons. Il s'agit d'un des plats les plus populaires en France, et s'il est souvent considéré comme une spécialité bourguignonne, le boeuf bourguignon est en réalité originaire de Paris. Servi dans les bouillons Duval à Paris en 1878, puis à la carte de nombreux restaurants et réceptions parisiennes dans la décennie des années 1880, la recette du boeuf bourguignon est codifiée par Auguste Escoffier dans son Guide culinaire en 1903, puis Auguste Colombié dans La cuisine bourgeoise en 1906.",

  `A l'origine, le Raclette du Valais est traditionnellement fondu au feu de bois, puis par des fours à raclette électriques depuis les années 1950. La raclette est consommée à ce jour au-delà du Valais, en Suisse (dont elle est un des emblèmes), et dans le monde, préparées avec des appareils de cuisson spécifiques, telle la raclette électrique, appelée "raclonette" en Suisse, notamment en Valais. Elle est posée en milieu de table et se compose d'un gril électrique (ou four à raclette), sous lequel viennent se poser des poêlons contenant le fromage à fondre, surmontée d'une plaque chauffante.`,

  "Le foufou (parfois fufu) est une pâte ou purée, solide ou molle selon le goût du consommateur, réalisée à partir de farines ou de tubercules bouillis et pilés. Il est fabriqué à partir de manioc, de maïs, de banane plantain ou d'igname, et se mange avec une sauce en accompagnement. Au Ghana, le fufu, également appelé fufuo, est blanc et collant (si la banane plantain n'est pas mélangée au manioc lors du pilonnage). La méthode traditionnelle de manger du fufu consiste à pincer une partie du fufu entre les doigts de la main droite et à en faire une boule ronde facilement ingérable. La balle est ensuite plongée dans la soupe avant d'être mangée.",

  "Un taco est un antojito (plat léger, collation) de la cuisine mexicaine qui se compose d'une tortilla de maïs garnie (avec en général plusieurs ingrédients typiques de la gastronomie mexicaine, dont une sauce) pliée en deux. Les tacos se mangent généralement sans couverts, avec les doigts. L'origine du taco remonte probablement au Mexique précolombien. Actuellement, au Mexique, les tacos sont le plat le plus consommé devant la pizza, et ses ventes représentent un moteur important de l'économie nationale, générant plusieurs dizaines de milliers d'emplois directs. Le taco est un des emblèmes internationaux du Mexique, avec les mariachis.",

  "Le saucisson est une spécialité charcutière incontournable dans la cuisine française, apprécié pour sa richesse de saveurs et sa diversité. Fabriqué à partir de viande de porc, parfois de volaille ou de boeuf, il est assaisonné avec des épices et des herbes, puis séché à l'air libre. La préparation du saucisson varie selon les régions, ce qui permet une multitude de goûts, allant du plus doux au plus épicé. Sa texture ferme et son goût prononcé en font un en-cas idéal, souvent dégusté lors de repas conviviaux ou d'apéritifs. Il se décline sous différentes formes : saucisson sec, saucisson de campagne, saucisson à l'ail, ou encore saucisson de Lyon. Traditionnellement, le saucisson est accompagné de pain, de fromage et de vin, ce qui le rend encore plus savoureux. Un incontournable de la gastronomie française, il incarne à la fois la simplicité et l'authenticité de la cuisine traditionnelle. Le saucisson est bien plus qu'un simple aliment, c'est un symbole de partage et de convivialité.",

  "Le cordon bleu est un plat délicieux qui allie simplicité et gourmandise. Il est traditionnellement préparé avec du poulet ou du veau, farci de jambon et de fromage, puis pané et frit. Ce mélange de textures - croquant à l'extérieur et fondant à l'intérieur - en fait un vrai délice. Le fromage, souvent du gruyère ou de l'emmental, se marie parfaitement avec le jambon, créant une harmonie de saveurs. Certaines variantes incluent des épices, des herbes ou même des légumes pour ajouter une touche originale. Il est fréquemment servi avec des frites, une purée ou des légumes de saison, ce qui en fait un plat complet et réconfortant. Lors des repas en famille ou entre amis, le cordon bleu fait toujours l'unanimité. Il incarne l'esprit de la cuisine française simple mais savoureuse, apportant à chaque bouchée une satisfaction garantie.",

  "La ratatouille est un plat provençal emblématique, qui mélange harmonieusement des légumes d'été comme les courgettes, les aubergines, les tomates et les poivrons. Ce plat est l'expression même de la cuisine méditerranéenne, légère et pleine de saveurs. La ratatouille est souvent mijotée lentement avec de l'huile d'olive, de l'ail et des herbes de Provence, pour libérer toute la richesse des légumes. C'est un plat idéal à servir en accompagnement ou en plat principal, qui peut être dégusté chaud ou froid. La ratatouille est un véritable hommage aux produits frais et de saison.",

  "Les escargots de Bourgogne sont une spécialité française raffinée, consommée lors de repas festifs. Préparés avec du beurre, de l'ail, du persil et parfois du vin blanc, les escargots sont cuits dans leurs coquilles et servis en entrée. Leur texture tendre et leur saveur délicatement parfumée par l'ail et le persil en font une expérience culinaire unique. Traditionnellement, ils sont accompagnés d'une baguette de pain pour saucer le beurre parfumé, ce qui complète à merveille ce plat emblématique de la cuisine bourguignonne.",


  // ---------------------------------------- Géographie ---------------------------------------- //
  "La tour Eiffel, emblème de la capitale française, a été construite entre 1887 et 1889 pour l'Exposition universelle de Paris. Avec ses 330 mètres de hauteur, elle a été pendant longtemps le plus haut monument du monde. Conçue par l'ingénieur Gustave Eiffel, cette structure métallique, bien qu'à l'origine critiquée pour son design audacieux, est aujourd'hui l'une des attractions touristiques les plus visitées au monde, attirant chaque année des millions de visiteurs venus admirer la vue imprenable sur Paris.",

  "Le Mont-Saint-Michel, situé en Normandie, est une merveille architecturale et un site classé au patrimoine mondial de l'UNESCO. Ce rocher solitaire émergeant de la mer abrite une abbaye médiévale impressionnante qui a été un centre spirituel majeur durant des siècles. Le Mont-Saint-Michel est également célèbre pour ses marées spectaculaires qui peuvent faire disparaître et réapparaître l'île, donnant lieu à des phénomènes naturels fascinants. Ce site attire les touristes du monde entier, fascinés par son histoire et sa beauté unique.",

  "Les pyramides d'Égypte, notamment la Grande Pyramide de Gizeh, sont parmi les structures les plus emblématiques de l'Antiquité. Ces monuments, construits il y a plus de 4 000 ans, servaient de tombes pour les pharaons et étaient destinées à assurer leur passage vers l'au-delà. Le savoir-faire des architectes et ouvriers de l'époque a permis de réaliser ces merveilles de l'ingénierie qui résistent encore aujourd'hui aux épreuves du temps, captivant les archéologues et les visiteurs du monde entier.",

  "Le Taj Mahal, situé à Agra en Inde, est un mausolée magnifique construit par l'empereur moghol Shah Jahan en mémoire de sa femme Mumtaz Mahal. Ce monument en marbre blanc est un chef-d'oeuvre de l'architecture moghole, combinant des éléments persans, turcs et indiens. Le Taj Mahal est également un symbole de l'amour éternel, et il attire chaque année des millions de visiteurs en raison de sa beauté et de son histoire émouvante. Classé au patrimoine mondial de l'UNESCO, il représente un des exemples les plus célèbres de l'architecture islamique dans le monde.",

  "L'Antarctique, continent gelé et presque inhabité, est le lieu le plus froid et le plus sec de la planète. Il contient environ 70 % de l'eau douce mondiale sous forme de glace. Bien que la vie humaine y soit presque inexistante en raison des conditions extrêmes, plusieurs stations de recherche scientifiques sont installées dans la région pour étudier la faune locale, notamment les manchots, ainsi que l'impact du changement climatique sur les calottes glaciaires. L'Antarctique joue un rôle crucial dans la régulation du climat terrestre et est essentiel pour la compréhension des dynamiques de la Terre.",

  "Le Louvre à Paris, le plus grand musée d'art au monde, abrite des milliers d'oeuvres d'art, allant de l'Antiquité à l'époque moderne. Ancienne résidence royale, le musée est devenu un centre culturel majeur après sa transformation en musée public en 1793. Parmi ses oeuvres les plus célèbres figurent la Joconde de Léonard de Vinci, la Vénus de Milo et la Victoire de Samothrace. Le Louvre est non seulement un lieu d'art et d'histoire, mais aussi un symbole du patrimoine culturel mondial. Chaque année, il attire des millions de visiteurs venus découvrir ses collections inestimables.",

  "Le Grand Canyon, situé en Arizona aux États-Unis, est une merveille naturelle créée par l'érosion du fleuve Colorado au cours des millions d'années. Ce canyon impressionnant, long de plus de 450 kilomètres et profond de plus de 1 800 mètres, est l'un des plus grands et des plus anciens du monde. Il est connu pour ses paysages spectaculaires, ses couleurs vibrantes et sa géologie fascinante. Le Grand Canyon est également un site spirituel important pour les peuples autochtones de la région et un lieu de prédilection pour les randonneurs et les amoureux de la nature.",

  "Le Nil, le plus long fleuve du monde, traverse plusieurs pays d'Afrique, notamment l'Égypte et le Soudan. Il a joué un rôle fondamental dans l'émergence de l'une des civilisations les plus anciennes de l'histoire humaine, celle de l'Égypte antique. Le fleuve fournissait une source d'eau vitale, ainsi que des voies de transport et de commerce, permettant le développement de l'agriculture dans la région. Aujourd'hui encore, le Nil est crucial pour la survie de millions de personnes vivant dans les pays qu'il traverse, fournissant de l'eau pour l'irrigation et servant de voie navigable.",

  "Les pyramides de Gizeh, en Égypte, sont l'une des sept merveilles du monde antique encore existantes. La plus célèbre d'entre elles, la Grande Pyramide, a été construite pour le pharaon Khéops au 26e siècle avant J.-C. Elle est un témoignage du génie architectural et des connaissances scientifiques des anciens Égyptiens. Construite avec des millions de blocs de pierre, la pyramide a servi de tombeau pour le pharaon, et son alignement avec les étoiles témoigne d'une compréhension avancée de l'astronomie. Aujourd'hui, ces pyramides attirent des millions de touristes et continuent de fasciner les archéologues et les historiens.",


  // ---------------------------------------- Histoire ---------------------------------------- //
  "La Seconde Guerre mondiale, qui a duré de 1939 à 1945, a profondément marqué l'histoire du XXe siècle. Elle a impliqué de nombreux pays à travers le monde, opposant les Alliés aux puissances de l'Axe. Les conséquences de ce conflit ont été dévastatrices, avec des millions de morts et une réorganisation radicale du monde. Les guerres et les combats ont eu lieu sur plusieurs continents, et des événements clés comme le Débarquement de Normandie ou la bataille de Stalingrad ont changé le cours de l'histoire. Après la guerre, la création de l'ONU et la Guerre froide ont modelé la politique internationale durant plusieurs décennies.",

  "La chute du mur de Berlin en 1989 est un événement historique majeur qui a symbolisé la fin de la Guerre froide et la réconciliation de l'Allemagne après des décennies de division. Le mur, construit en 1961 par le régime est-allemand, séparait Berlin en deux, empêchant les citoyens de l'Allemagne de l'Est de fuir vers l'Ouest. Sa chute a marqué le début d'une nouvelle ère pour l'Europe de l'Est, ouvrant la voie à la réunification de l'Allemagne et à la dissolution de l'Union soviétique. Le mur est désormais un symbole de liberté et de l'importance de l'unité humaine.",

  // ---------------------------------------- Jeux-vidéos ---------------------------------------- //
  "Les premiers jeux vidéo remontent aux années 1950, mais c'est en 1972 que l'industrie a pris son envol avec la création de Pong, un jeu d'arcade simple mais innovant, développé par Atari. Ce jeu de tennis de table a été un succès immédiat et a marqué le début de l'ère des jeux vidéo commerciaux. Depuis, l'industrie a connu une croissance phénoménale, évoluant de simples jeux d'arcade à des expériences immersives en 3D avec des graphismes réalistes, des mondes ouverts, et des scénarios de plus en plus complexes.",

  "La saga Super Mario, créée par Nintendo, est l'une des franchises les plus emblématiques du monde du jeu vidéo. Le premier jeu Super Mario Bros. est sorti en 1985 sur la console NES et a révolutionné les jeux de plateforme. Avec Mario, Luigi et la Princesse Peach, cette série a non seulement redéfini le genre, mais a également propulsé Nintendo en tant qu'acteur majeur de l'industrie. La franchise a engendré de nombreux jeux, films, séries, et même des attractions à thème, et Mario est devenu une icône mondiale du jeu vidéo.",

  "L'émergence de Minecraft, développé par Mojang en 2009, a marqué un tournant dans l'industrie des jeux vidéo. Ce jeu de construction en monde ouvert a rapidement capturé l'imaginaire des joueurs grâce à sa simplicité, son monde pixelisé et ses possibilités infinies. À travers sa créativité et son mode multijoueur, Minecraft est devenu l'un des jeux les plus vendus de tous les temps, influençant non seulement le secteur des jeux vidéo, mais aussi l'éducation, l'architecture et l'art.",

  "Le jeu The Legend of Zelda: Ocarina of Time, sorti en 1998 sur la Nintendo 64, est souvent considéré comme l'un des meilleurs jeux vidéo de tous les temps. Avec son gameplay innovant, son monde ouvert et ses éléments narratifs profonds, ce jeu a marqué une révolution dans la façon dont les jeux d'aventure étaient conçus. Son impact est encore visible aujourd'hui, avec de nombreux jeux modernes qui s'inspirent de ses mécaniques. Il a également introduit des éléments de narration et de résolution d'énigmes qui sont devenus des standards dans l'industrie.",

  "Le e-sport (sport électronique) est un secteur en pleine expansion qui regroupe des compétitions de jeux vidéo au niveau professionnel. Des jeux comme League of Legends, Dota 2, Counter-Strike et Fortnite attirent des millions de spectateurs, tandis que les meilleurs joueurs professionnels sont devenus de véritables célébrités. L'e-sport est même devenu un événement majeur avec des ligues et des tournois internationaux, des prix en argent impressionnants et une couverture médiatique croissante. Ce phénomène a changé la perception des jeux vidéo, les transformant en un sport à part entière.",



  // ---------------------------------------- Sport ---------------------------------------- //
  "Les Jeux Olympiques modernes, inspirés des anciens jeux olympiques grecs, ont été rétablis en 1896 à Athènes. Depuis, les JO ont lieu tous les quatre ans et réunissent des athlètes du monde entier pour une compétition internationale. Le nombre de sports présents a considérablement augmenté au fil des ans, avec des sports comme le basket-ball, le tennis et même le skateboard récemment ajoutés. L'esprit olympique met en avant la paix, la fraternité et l'unité mondiale à travers le sport.",

  "Le basket-ball, inventé en 1891 par James Naismith à Springfield, Massachusetts, est devenu l'un des sports les plus populaires du monde. Son développement rapide aux États-Unis a conduit à la formation de la NBA (National Basketball Association) en 1946. Des joueurs légendaires comme Michael Jordan, Kobe Bryant, et LeBron James ont transcendé ce sport, attirant des millions de fans dans le monde entier et en faisant une véritable culture de spectacle sportif, avec des matchs diffusés globalement et un engouement phénoménal.",

  "Le Tour de France, l'une des courses cyclistes les plus prestigieuses au monde, a été créé en 1903 par le journal L'Auto afin d'augmenter ses ventes. Depuis lors, il est devenu une tradition annuelle qui attire des millions de spectateurs, tant en France qu'à l'international. Ce défi de trois semaines est considéré comme l'une des compétitions les plus difficiles dans le sport cycliste, combinant endurance, stratégie et maîtrise technique des terrains montagneux. Des figures emblématiques comme Eddy Merckx, Bernard Hinault, et plus récemment Chris Froome ont marqué son histoire.",

  "Le football américain, né aux États-Unis à la fin du 19e siècle, est devenu un phénomène culturel majeur. La National Football League (NFL) a été fondée en 1920 et a rapidement gagné en popularité. Le Super Bowl, la finale annuelle de la NFL, est l'un des événements sportifs les plus regardés au monde, non seulement pour le football mais aussi pour les spectacles de mi-temps et les publicités de grande envergure. Des joueurs comme Joe Montana, Tom Brady et Peyton Manning sont devenus des légendes, et la NFL continue de captiver des millions de fans à travers le monde.",

  "Le cricket est l'un des sports les plus populaires dans des pays comme l'Inde, l'Angleterre, l'Australie et le Pakistan. Bien qu'il soit joué depuis des siècles, le cricket moderne a évolué au 20e siècle avec l'introduction du format des matches de 20 overs, connu sous le nom de Twenty20 (T20). Ce format rapide et spectaculaire a permis au cricket de toucher un public plus large, avec des compétitions comme la Indian Premier League (IPL) qui attire aujourd'hui des millions de spectateurs à travers le monde. Le cricket est plus qu'un sport, c'est un véritable phénomène culturel dans de nombreux pays.",

  "Le rugby, sport d'équipe où deux équipes s'affrontent pour marquer des essais avec un ballon ovale, est particulièrement populaire en Nouvelle-Zélande, en Angleterre, en France et en Australie. Le *Haka*, danse traditionnelle maorie réalisée par l'équipe néo-zélandaise avant chaque match, est l'une des traditions les plus emblématiques du rugby. La Coupe du Monde de Rugby, qui se déroule tous les quatre ans, est l'un des événements sportifs les plus regardés dans le monde, avec une immense ferveur qui entoure chaque édition."
];
