export const foodTextsFr = [
    "La baguette de pain maison, emblème de la boulangerie française, incarne à la fois la simplicité et l'excellence artisanale. Cette recette iconique, réalisée avec quelques ingrédients de base, offre une expérience culinaire authentique et gratifiante. Pétrir la pâte à la main, sentir les arômes du pain frais emplir la cuisine, puis déguster une baguette croustillante à la sortie du four sont des moments de pure satisfaction.",

    "Le boeuf bourguignon est un plat de viande de boeuf braisée au vin rouge, et servi avec une garniture composée d'oignons grelots, de champignons et de lardons. Il s'agit d'un des plats les plus populaires en France, et s'il est souvent considéré comme une spécialité bourguignonne, le boeuf bourguignon est en réalité originaire de Paris. Servi dans les bouillons Duval à Paris en 1878, puis à la carte de nombreux restaurants et réceptions parisiennes dans la décennie des années 1880, la recette du boeuf bourguignon est codifiée par Auguste Escoffier dans son Guide culinaire en 1903, puis Auguste Colombié dans La cuisine bourgeoise en 1906.",

    `A l'origine, le Raclette du Valais est traditionnellement fondu au feu de bois, puis par des fours à raclette électriques depuis les années 1950. La raclette est consommée à ce jour au-delà du Valais, en Suisse (dont elle est un des emblèmes), et dans le monde, préparées avec des appareils de cuisson spécifiques, telle la raclette électrique, appelée "raclonette" en Suisse, notamment en Valais. Elle est posée en milieu de table et se compose d'un gril électrique (ou four à raclette), sous lequel viennent se poser des poêlons contenant le fromage à fondre, surmontée d'une plaque chauffante.`,

    "Le foufou (parfois fufu) est une pâte ou purée, solide ou molle selon le goût du consommateur, réalisée à partir de farines ou de tubercules bouillis et pilés. Il est fabriqué à partir de manioc, de maïs, de banane plantain ou d'igname, et se mange avec une sauce en accompagnement. Au Ghana, le fufu, également appelé fufuo, est blanc et collant (si la banane plantain n'est pas mélangée au manioc lors du pilonnage). La méthode traditionnelle de manger du fufu consiste à pincer une partie du fufu entre les doigts de la main droite et à en faire une boule ronde facilement ingérable. La balle est ensuite plongée dans la soupe avant d'être mangée.",

    "Un taco est un antojito (plat léger, collation) de la cuisine mexicaine qui se compose d'une tortilla de maïs garnie (avec en général plusieurs ingrédients typiques de la gastronomie mexicaine, dont une sauce) pliée en deux. Les tacos se mangent généralement sans couverts, avec les doigts. L'origine du taco remonte probablement au Mexique précolombien. Actuellement, au Mexique, les tacos sont le plat le plus consommé devant la pizza, et ses ventes représentent un moteur important de l'économie nationale, générant plusieurs dizaines de milliers d'emplois directs. Le taco est un des emblèmes internationaux du Mexique, avec les mariachis.",

    "Le saucisson est une spécialité charcutière incontournable dans la cuisine française, apprécié pour sa richesse de saveurs et sa diversité. Fabriqué à partir de viande de porc, parfois de volaille ou de boeuf, il est assaisonné avec des épices et des herbes, puis séché à l'air libre. La préparation du saucisson varie selon les régions, ce qui permet une multitude de goûts, allant du plus doux au plus épicé. Sa texture ferme et son goût prononcé en font un en-cas idéal, souvent dégusté lors de repas conviviaux ou d'apéritifs. Il se décline sous différentes formes : saucisson sec, saucisson de campagne, saucisson à l'ail, ou encore saucisson de Lyon. Traditionnellement, le saucisson est accompagné de pain, de fromage et de vin, ce qui le rend encore plus savoureux. Un incontournable de la gastronomie française, il incarne à la fois la simplicité et l'authenticité de la cuisine traditionnelle. Le saucisson est bien plus qu'un simple aliment, c'est un symbole de partage et de convivialité.",

    "Le cordon bleu est un plat délicieux qui allie simplicité et gourmandise. Il est traditionnellement préparé avec du poulet ou du veau, farci de jambon et de fromage, puis pané et frit. Ce mélange de textures - croquant à l'extérieur et fondant à l'intérieur - en fait un vrai délice. Le fromage, souvent du gruyère ou de l'emmental, se marie parfaitement avec le jambon, créant une harmonie de saveurs. Certaines variantes incluent des épices, des herbes ou même des légumes pour ajouter une touche originale. Il est fréquemment servi avec des frites, une purée ou des légumes de saison, ce qui en fait un plat complet et réconfortant. Lors des repas en famille ou entre amis, le cordon bleu fait toujours l'unanimité. Il incarne l'esprit de la cuisine française simple mais savoureuse, apportant à chaque bouchée une satisfaction garantie.",

  ];
  