export const wordsEn = [
  "love", "peace", "harmony", "joy", "freedom", "hope", "light", "wisdom", "strength",
  "life", "reality", "nature", "beauty", "friendship", "truth", "serenity", "dream", "trust",
  "future", "instant", "memory", "sweetness", "courage", "balance", "progress", "star",
  "universe", "rainbow", "creativity", "thought", "mystery", "solidarity", "sharing",
  "happiness", "respect", "energy", "inspiration", "equality", "fraternity", "discovery",
  "gratitude", "depth", "listen", "calm", "travel", "poetry", "song", "horizon",
  "sun", "sea", "mountain", "river", "forest", "flower", "season", "morning", "evening",
  "reflection", "wind", "earth", "rain", "fire", "air", "moon", "cloud", "heat", "ice",
  "sand", "passion", "humanity", "union", "will", "heart", "soul", "spirit", "destiny",
  "infinity", "shine", "shadow", "breathing", "awakening", "search", "enigma", "connection",
  "synergy", "idea", "concept", "rebirth", "metamorphosis", "link", "creation", "symbiosis",
  "choice", "way", "message", "consciousness", "history", "doubt", "encounter", "destiny",
  "fusion", "moment", "hope", "wonder", "essential", "space", "answer",
  "question", "exploration", "reflection", "resonance", "commitment", "symphony", "legend",
  "memory", "day", "promise", "quest", "glow", "passage", "vision", "perspective",
  "adaptation", "emotion", "solution", "greatness", "vibration", "prosperity", "commitment",
  "unity", "vibration", "progress", "sensation", "harmony",
  "perseverance", "clairvoyance", "initiative", "society", "dynamism", "efficiency",
  "benevolence", "audacity", "creativity", "flourishing", "optimism", "authenticity",
  "curiosity", "ethics", "innovation", "reciprocity", "openness", "equity", "diversity",
  "generosity", "altruism", "tolerance", "integrity", "perseverance", "momentum",
  "introspection", "dignity", "emancipation", "visionary", "spontaneity",
  "intuition", "resilience", "elegance", "power", "stability", "happiness",
  "intensity", "fullness", "charisma", "sensitivity", "contemplation", "craze",
  "harmonization", "solidity", "completeness", "discipline", "heroism", "modesty", "creation",
  "meditation", "resolution", "insight", "sublimity", "celebration", "lightness",
  "fireplace", "raclette", "cactus", "sheepfold", "pig", "zebra", "giraffe", "cat", "dog",
  "tackle", "turkey", "duck", "pigeon", "bird", "hen", "cow", "sheep", "goat",
  "console", "desk", "table", "chair", "sofa", "bed", "sofa", "carpet", "diapers",
  "tulip", "rose", "sunflower", "purple", "blue", "green", "yellow", "red", "black", "white",
  "gold", "silver", "pokemon", "cave", "room", "bedroom", "bathroom", "minecraft", "valorant",
  "fortnite", "lego", "trout", "salmon", "fly", "a", "one", "of", "these", "their", "theirs",
  "color", "man", "woman", "marriage", "birth", "berserk", "vampire", "zombie", "blood",
  "death", "pain", "keyboard", "computer", "headphones", "earphones", "microphone", "doorbell",
  "delivery", "car", "van", "motorcycle", "truck", "kart", "bike", "bicycle",
  "watermelon", "melon", "banana", "apple", "orange", "lemon", "apricot", "strawberry", "raspberry",
  "number", "digit", "symbol", "jacket", "shirt", "shorts", "jeans", "pants", "shirt",
  "circle", "square", "rectangle", "triangle", "alcohol", "tobacco", "cigarette", "coffee", "tea",
  "lasagna", "kebab", "steak", "pizza", "spaghetti", "chocolate", "cheese", "apples", "bananas",
  
  ];