export const wordsFr = [
  "amour", "paix", "harmonie", "joie", "liberté", "espoir", "lumière", "sagesse", "force",
  "vie", "réalité", "nature", "beauté", "amitié", "vérité", "sérénité", "rêve", "confiance",
  "avenir", "instant", "souvenir", "douceur", "courage", "équilibre", "progrès", "étoile",
  "univers", "arc-en-ciel", "créativité", "pensée", "mystère", "solidarité", "partage",
  "bonheur", "respect", "énergie", "inspiration", "égalité", "fraternité", "découverte",
  "gratitude", "profondeur", "écoute", "calme", "voyage", "poésie", "chanson", "horizon",
  "soleil", "mer", "montagne", "rivière", "forêt", "fleur", "saison", "matin", "soir",
  "reflet", "vent", "terre", "pluie", "feu", "air", "lune", "nuage", "chaleur", "glace",
  "sable", "passion", "humanité", "union", "volonté", "cœur", "âme", "esprit", "destin",
  "infini", "éclat", "ombre", "respiration", "éveil", "recherche", "énigme", "connexion",
  "synergie", "idée", "concept", "renaissance", "métamorphose", "lien", "création", "symbiose",
  "choix", "voie", "message", "conscience", "histoire", "doute", "rencontre", "destinée",
  "fusion", "moment", "espérance", "émerveillement", "essentiel", "espace", "réponse",
  "question", "exploration", "réflexion", "résonance", "engagement", "symphonie", "légende",
  "mémoire", "jour", "promesse", "quête", "lueur", "passage", "vision", "perspective",
  "adaptation", "émotion", "solution", "grandeur", "vibration", "prospérité", "engagement",
  "unité", "vibration", "progrès", "sensation", "harmonie", 
  "persévérance", "clairvoyance", "initiative", "société", "dynamisme", "efficacité",
  "bienveillance", "audace", "créativité", "épanouissement", "optimisme", "authenticité",
  "curiosité", "éthique", "innovation", "réciprocité", "ouverture", "équité", "diversité",
  "générosité", "altruisme", "tolérance", "intégrité", "persévérance", "élan", "motivation",
  "introspection", "dignité", "émancipation", "visionnaire", "spontanéité",
  "intuition", "résilience", "élégance", "puissance", "stabilité", "félicité",
  "intensité", "plénitude", "charisme", "sensibilité", "contemplation", "engouement",
  "harmonisation", "solidité", "complétude", "discipline", "héroïsme", "modestie", "création",
  "méditation", "résolution", "perspicacité", "sublimité", "célébration", "légèreté",
  "cheminée", "raclette", "cactus", "bergerie", "cochon", "zèbre", "girafe", "chat", "chien",
  "tacle", "dinde", "canard", "pigeon", "oiseau", "poule", "vache", "mouton", "chevre",
  "console", "bureau", "table", "chaise", "sofa", "lit", "canape", "tapis", "couches",
  "tulipe", "rose", "tournesol", "violet", "bleu", "vert", "jaune", "rouge", "noir", "blanc",
  "or", "argent", "pokemon", "caverne", "salle", "chambre", "salle de bain", "minecraft", "valorant",
  "fortnite", "lego", "truite", "saumon", "mouche", "une", "un", "des", "ces", "leur", "leurs",
  "couleur", "homme", "femme", "mariage", "naissance", "berserk", "vampire", "zombie", "sang",
  "mort", "douleur", "clavier", "ordinateur"," casque", "écouteurs", "microphone", "sonnette",
  "livraison", "voiture", "camionnette", "moto", "camion", "kart", "vélo", "bicyclette",
  "pastèque", "melon", "banane", "pomme", "orange", "citron", "abricot", "fraise", "framboise",
  "numéro", "chiffre", "symbole", "veste", "chemise", "short", "jean", "pantalon", "chemise", 
  "cercle", "carre", "rectangle", "triangle", "alcool", "tabac", "cigarette", "cafe", "the",
  "lasagne", "kebab", "steak", "pizza", "spaghetti", "chocolat", "fromage", "pommes", "bananes",
  
];
